# version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: nosql_project
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flaskapp:
    build: ./
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongo_data:
